### ISSUE TITLE
Update the network filter to have a drop down

### ISSUE THREAD

**Issue by lazycoder1** [jiffy-labs/jiffyscan-frontend#14]
Currently , we have four badges for four different networks that are supported. 

### Desktop view:
<img width="474" alt="Screenshot 2023-03-19 at 1 47 59 AM" src="https://user-images.githubusercontent.com/10191561/226136315-b101e591-94b9-4929-8b10-a28b51169d41.png">

### Mobile view: 
<img width="441" alt="Screenshot 2023-03-19 at 1 50 11 AM" src="https://user-images.githubusercontent.com/10191561/226136394-0e7bfeb8-8c88-4d5e-9b24-028fa7ca0516.png">

This will need to be updated as per the design specs 
https://www.figma.com/file/qNnGRS1hqfKjZglejMthRP/Handouts?node-id=1%3A2485&t=sxuQoVtP7zLv3RoU-1

### Desktop view: 
<img width="394" alt="Screenshot 2023-03-19 at 1 51 14 AM" src="https://user-images.githubusercontent.com/10191561/226136592-2d7312b5-3eac-4b26-ba05-87d4358f0af3.png">

### Mobile view:
<img width="388" alt="Screenshot 2023-03-19 at 1 51 34 AM" src="https://user-images.githubusercontent.com/10191561/226136657-46e0b196-84c6-480b-ae84-235c3f0386e0.png">

Where clicking on more gives a drop-down of all the supported networks to filter from. 

This is needed so we can increase the number of supported networks without it filling up the screen. 

Note: Current development directory is `ui-work` , it can be clone to view the latest change in dev

**Comment by DonFungible** [comment]
Am a bit confused where you got the first two images that has the "Mainnet" button. The current `master` branch seems to match the Figma.

Screenshot of Figma:
<img width="505" alt="image" src="https://user-images.githubusercontent.com/100505855/226137238-0379ef0b-b81d-451e-a8f4-ce86dfc8cb4f.png">

Screenshot of frontend in `master`:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/100505855/226137302-3f9b6858-6049-4d88-9acf-1963daecd2b4.png">

**Comment by lazycoder1** [comment]
The code is present in the `ui-work` branch. The development code has not been merged to master yet

**Comment by DonFungible** [comment]
Please try the dropdown functionality from my branch. Thanks

https://github.com/jiffy-labs/jiffyscan-frontend/pull/15

**Comment by lazycoder1** [comment]
Major part of the work is done, but there is still a minor issue when you switch from mobile view to desktop view. 

I will keep this issue open for that. 

###Issue:

![Screenshot 2023-03-23 at 12 54 40 PM](https://user-images.githubusercontent.com/10191561/227132252-51b034db-c6f8-4930-a717-2d6f19636fbd.png)

The UI seems like multiple networks are selected. In-terms of functionality nothing is impacted.

### Steps to reproduce error:
1. Switch to mobile view, and select a network from the dropdown.
![Screenshot 2023-03-23 at 12 53 41 PM](https://user-images.githubusercontent.com/10191561/227132108-a1ff04cf-5ae8-4de6-a382-8eb5b6444509.png)

2. Switch to desktop view
![Screenshot 2023-03-23 at 12 54 40 PM](https://user-images.githubusercontent.com/10191561/227132252-51b034db-c6f8-4930-a717-2d6f19636fbd.png)

**Comment by DonFungible** [comment]
Completed with PR #39
