### ISSUE TITLE
Unable to switch to ui-work branch: invalid-reference error

### ISSUE THREAD

**Issue by NIKHILNAIR21** [jiffy-labs/jiffyscan-frontend#154]
I am trying to contribute to the Jiffyscan project and follow the getting started guide. However, when I attempt to switch to the ui-work branch, I encounter an invalid-reference: uiwork error.

steps i followed

1)Cloned the repository using git clone https://github.com/jiffy-labs/jiffyscan-frontend.git
2)Navigated to the repository directory: cd jiffyscan-frontend
3)Tried to switch to the ui-work branch: git switch ui-work && git pull

result:
fatal:invalid-reference: ui-work

I also tried listing all branches with git branch -a, but could not find ui-work.
Could you please confirm the correct branch name or provide guidance on how to resolve this issue?

**Comment by Ojas13-git** [comment]
Hey @NIKHILNAIR21 ,
You can work on the development branch and create a fork off the development branch, make changes and raise a PR to development.
Thanks for contributing :)
