### ISSUE TITLE
[Home page]Remove blur when you open the drop down

### ISSUE THREAD

**Issue by lazycoder1** [jiffy-labs/jiffyscan-frontend#16]
Currently there is a blue effect when you open the drop down in the search bar. This needs to be removed since it's distracting to the mind.

**Comment by Aremu-olusegun** [comment]
Can i take on this issue?

**Comment by Aremu-olusegun** [comment]
I can't seem to find any dropdown at the search bar?

**Comment by lazycoder1** [comment]
Can you check it out in the `ui-work` branch ?

**Comment by Aremu-olusegun** [comment]
Thanks

**Comment by Aremu-olusegun** [comment]
Hello, i got this error while trying to push to the repo

git push --set-upstream origin ui-work
remote: Permission to jiffy-labs/jiffyscan-frontend.git denied to Aremu-olusegun.
fatal: unable to access 'https://github.com/jiffy-labs/jiffyscan-frontend.git/': The requested URL returned error: 403

Please how do i work around this error.

**Comment by vintageplayer** [comment]
> Hello, i got this error while trying to push to the repo
> 
> git push --set-upstream origin ui-work remote: Permission to jiffy-labs/jiffyscan-frontend.git denied to Aremu-olusegun. fatal: unable to access 'https://github.com/jiffy-labs/jiffyscan-frontend.git/': The requested URL returned error: 403
> 
> Please how do i work around this error.

You cannot directly push changes to this repository. You will have to fork the repository in github to your own profile. Update the changes to that repository and create a PR to the appropriate branch here.

**Comment by Aremu-olusegun** [comment]
pull request have been made 

Thanks @vintageplayer

**Comment by lazycoder1** [comment]
Thanks @Aremu-olusegun for the change. Do let me know if you would like to pick up more issues in future 
( telegram @lazyc0der1 )
