### ISSUE TITLE
[Bug] Overlapping Dropdown Menus

### ISSUE THREAD

**Issue by mananpatel06** [jiffy-labs/jiffyscan-frontend#164]
Bug details 
On a smaller screen device, the drop-down menu for selecting the chain overlaps with other drop-down menu on the page.

Steps to reproduce the bug
open website in smaller screen device (smartphone) and click on ⚡( drop-down ).

Expected behavior
Dropdown menu should not overlap. 

Actual behavior
Dropdown menus are overlapping.

Screenshot 👇

![issues](https://github.com/user-attachments/assets/80f7ce2e-79d6-4fe5-8a25-c78b21afedb9)

**Comment by mananpatel06** [comment]
@lazycoder1 can i work on this issue ??

**Comment by lazycoder1** [comment]
Yes @mananpatel06 , please give it a shot. Much appreciated.

**Comment by mananpatel06** [comment]
@lazycoder1 Ready for merge.

**Comment by Ojas13-git** [comment]
Thanks for contributing @mananpatel06.
