### ISSUE TITLE
Update gas fee information in the charts

### ISSUE THREAD

**Issue by lazycoder1** [jiffy-labs/jiffyscan-frontend#36]
Currently gas fee collected is being displayed with the entire number 

<img width="317" alt="Screenshot 2023-03-24 at 5 10 59 PM" src="https://user-images.githubusercontent.com/10191561/227513156-71fb994a-4533-478a-9173-437b8ac638e6.png">

It's quite hard to read when the number is so big. 

We need to reduce the number being shown to a different value. 

For now, we can reduce the number to ETH ( number / 10^18 ).

**Comment by DonFungible** [comment]
Is this solved now? Looks like L96 of utils.tsx divides the number by 10**18
