### ISSUE TITLE
Add Arbitrum Goerli

### ISSUE THREAD

**Issue by jacque006** [jiffy-labs/jiffyscan-frontend#56]
It would be nice to have [Arbitrum Goerli](https://chainlist.org/chain/421613) as a supported network for looking at ERC-4337 stats.

Current networks:
![image](https://user-images.githubusercontent.com/10394161/229933686-25198f29-0fe6-4150-bbe5-66a1b9a2fc6a.png)
![image](https://user-images.githubusercontent.com/10394161/229933532-db3f78d8-6e9a-4341-8f60-d7cbbc927891.png)

**Comment by lazycoder1** [comment]
We are currently using Graph Protocol as our backend to index the blockchain. As of writing this comment, the graph does not support [arbitrum-goerli](https://thegraph.com/docs/en/developing/supported-networks/).

We shall however pick up the task of setting up the node for arbitrum goerli and soon start indexing it. But it will take us a few weeks to get this network out.

**Comment by vintageplayer** [comment]
@lazycoder1 Graph Hosted Service supports arbitrum-goerli.

@jacque006 Have lined up support for arbitrum-goerli. Should have it out with this week's updates.

**Comment by vintageplayer** [comment]
The network is added: https://app.jiffyscan.xyz/?network=arbitrum-goerli
