### ISSUE TITLE
Create a page to list of bundlers

### ISSUE THREAD

**Issue by lazycoder1** [jiffy-labs/jiffyscan-frontend#81]
Columns to Create:
1. Bundler Address
2. Total Number of UserOps
3. Total Fee Paid
4. Total Fee Collected
5. Average Markup Per UserOp
6. Bundler Branding

### Logic For Calculation Average Markup Per UserOp
Bundle 1
	0.003
	0.005
	0.006
Total: 0.014
Bundler Paid (Txn Fee): 0.009
Markup: ((0.014-0.009)/0.009) = 55.55%

Bundle 2
	0.007
Total: 0.007
Bundler Paid: 0.008
Markup: ((0.008-0.007)/0.007) = 14.28%

Average Markup: (0.5555*3+0.1428)/4 = 45.23%

Calculating the Total Fee Collected vs Total Fee Paid Will not give an accurate per UserOp Markup.
For eg, In the above scenario:
Total Fee Paid: 0.009+0.008 = 0.017
Total Fee Collected: 0.014 +0.007 = 0.021
Overall Markup: (0.021-0.017)/0.017 = 23.53%

This would be incorrect as we want to given insight on perUser level

**Comment by vintageplayer** [comment]
Possible Way to maintain average markup using subgraphs:

Scenario 1: New User Op and a New Bundle
	Set #UserOp in Bundle = 1
	Set Total BundleFeeCollected 
	Set Total FeePaidByBundler 
	Calculate AvgMarkupPerUserOp

	Bundler
	 - Total number of UserOps (old)
	 - Average Markup for UserOp (Old)

	New Average Markup = (old_markup*NumUserOpsOld + AvgMarkup*1)/(NumUserOpsOld+1)
	TotalNumber of Userop += 1 


Scenario 2: New UserOp for an existing Bundle

	New #UserOp in Bundle += 1
	Update Total BundleFeeCollected += UserOp Actual Gas Cost 
	Total FeePaidByBundler Remains Unchanged
	Save Old AvgMarkupPerUserOp
	Calculate AvgMarkupPerUserOp

	Bundler
	 - Total number of UserOps (old)
	 - Average Markup for UserOp (Old)

	New Average Markup = (old_markup*NumUserOpsOldBundle - old_avergageMarkupBundler*OldNumberOfUserOpsBundle + AvgMarkupBundle*NewNumberofUserOpsBundle)/(NumUserOpsOldBundler+1)
	TotalNumberBundler of Userop += 1

**Comment by lazycoder1** [comment]
This has been completed but instead of avg. mark up , I am currently showing Sum of actualGasCost of all user ops. I'll take it a task to modify it to avg mark up later on. 

- https://jiffyscan-frontend-c395cjfhr-jiffy-labs.vercel.app/bundlers?network=goerli 

Looking at the data , the transaction fee doesn't seem to be picked up properly.
- https://api.thegraph.com/subgraphs/name/lazycoder1/optimism-jiffy-scan/graphql?query=query+MyQuery+%7B%0A++bundlers%28first%3A+10%29+%7B%0A++++avgMarkUp%0A++++address%0A++++transactionFeeSum%0A++++userOpsLength%0A++++actualGasCostSum%0A++%7D%0A%7D
