### ISSUE TITLE
Breadcrumbs font is incorrect

### ISSUE THREAD

**Issue by mzemlickis** [jiffy-labs/jiffyscan-frontend#91]
The wrong font in breadcrumbs. Right one is the Roboto

<img width="397" alt="image" src="https://github.com/jiffy-labs/jiffyscan-frontend/assets/4556944/8f462de9-4edc-45fc-ba21-3a3fac1ad0e7">

**Comment by YubaNeupane** [comment]
can i get assigned to this?
