### ISSUE TITLE
Non existing hover on currency tag

### ISSUE THREAD

**Issue by mzemlickis** [jiffy-labs/jiffyscan-frontend#94]
On the desktop on hover, it shows up a cursor for the link, but there is no link

<img width="185" alt="image" src="https://github.com/jiffy-labs/jiffyscan-frontend/assets/4556944/e595e685-5097-432e-a6bb-edaaa97b732b">

**Comment by YubaNeupane** [comment]
can i get assigned to this?

**Comment by YubaNeupane** [comment]
@lazycoder1 ready for merge!
