### ISSUE TITLE
Sort is not fuctional, maybe removing hover pointer

### ISSUE THREAD

**Issue by mzemlickis** [jiffy-labs/jiffyscan-frontend#97]
The sorting needs to be fixed. Maybe as a quick fix just to remove the hover pointer for now.

<img width="1281" alt="image" src="https://github.com/jiffy-labs/jiffyscan-frontend/assets/4556944/2bbc7da6-2990-487d-814e-6a2716f0f114">

**Comment by dheerajsingh0** [comment]
Please give me a bit deep info about the issue.?

**Comment by mzemlickis** [comment]
@dheerajsingh0 now you can cover over age, and it gives a pointer cursor, but once you click nothing happens

**Comment by lazycoder1** [comment]
We can remove the icon as of right now. I had created it to show that the age is sorted.
